### ISSUE TITLE
Firmware.

### ISSUE THREAD

**Issue by malinin24** [jmdaly/steamvan#2]
Hello.
Great job!
I want to assemble a cuatom numpad, came across your development, it will greatly speed up the process.
But I did not find a mention of the firmware.
Where can I get it? Are there sources?

**Comment by jmdaly** [comment]
Hi there, thank you for checking out the project! This project runs on the QMK firmware. It's a popular open source keyboard firmware. You can find their site [here](https://qmk.fm/).  The particulars for the SteamVan in QMK can be found [here](https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/steamvan). Hope that helps!

**Comment by malinin24** [comment]
Cool!
Apparently I have not yet reached the QMK on stm32, now I saw it.
Many thanks again and success!
